### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by bitca-andrei** [bbeesley/hygen-cook#113]
After namespace support is added (#102), alias support for ingredients can be added, while also allowing array of strings on the ingredients (without alias):

```yml
ingredients:
  - alias: sdh
     repo: https://github.com/hygen-generators/scaffolder-demo-hygen
  - alias: gag
     name: github-actions-generators
instructions:
  - ingredient: sdh
    generator: monorepo
    action: new
    args:
      - option: name
        value: simple-service
 - ingredient: gag
    generator: github-actions
    action: build-test-publish
    args:
      - option: admin-github-token
        value: SUPER_SECRET_TOKEN
      - option: main-branch
        value: main
      - option: node-version
        value: '14.11'
      - option: use-commit-lint
      - option: use-lerna
```
