### ISSUE TITLE
Add support for locking to a specific ingredient version

### ISSUE THREAD

**Issue by bitca-andrei** [bbeesley/hygen-cook#115]
Also allow option to specify ingredients as an array of strings:

```
ingredients:
  - https://github.com/hygen-generators/scaffolder-demo-hygen
  - name: github-actions-generators
    version: 1.0.0
```
